// <auto-generated />
using FinsaWeb.Models.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FinsaWeb.Migrations
{
    [DbContext(typeof(FinsaContext))]
    partial class FinsaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinsaWeb.Models.Allievo", b =>
                {
                    b.Property<int>("IdStudente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodiceFiscale");

                    b.Property<string>("Cognome");

                    b.Property<string>("Nome");

                    b.Property<string>("TipoStudente");

                    b.HasKey("IdStudente");

                    b.ToTable("Allievi");
                });
#pragma warning restore 612, 618
        }
    }
}
