// <auto-generated />
using FinsaWeb.Models.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FinsaWeb.Migrations
{
    [DbContext(typeof(FinsaContext))]
    partial class FinsaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CorsoAllievo", b =>
                {
                    b.Property<int>("IDAllievo");

                    b.Property<int>("IDEdizioneCorso");

                    b.Property<int?>("Voto");

                    b.HasKey("IDAllievo", "IDEdizioneCorso");

                    b.HasIndex("IDEdizioneCorso");

                    b.ToTable("CorsiAllievi");
                });

            modelBuilder.Entity("FinsaWeb.Models.Allievo", b =>
                {
                    b.Property<int>("IdStudente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodiceFiscale");

                    b.Property<string>("Cognome");

                    b.Property<string>("Nome");

                    b.Property<string>("TipoStudente");

                    b.HasKey("IdStudente");

                    b.ToTable("Allievi");
                });

            modelBuilder.Entity("FinsaWeb.Models.Corso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Difficolta");

                    b.Property<decimal?>("PrezzoBase");

                    b.Property<string>("Titolo");

                    b.HasKey("Id");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("FinsaWeb.Models.CorsoDocente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("CorsiDocenti");
                });

            modelBuilder.Entity("FinsaWeb.Models.Docente", b =>
                {
                    b.Property<int>("IDDocente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CF");

                    b.Property<string>("Cognome");

                    b.Property<DateTime>("DataNascita");

                    b.Property<string>("Nome");

                    b.Property<string>("TipoDocente");

                    b.HasKey("IDDocente");

                    b.ToTable("Docenti");
                });

            modelBuilder.Entity("FinsaWeb.Models.EdizioneCorso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataInizio");

                    b.Property<int>("IdCorso");

                    b.HasKey("Id");

                    b.ToTable("EdizioniCorsi");
                });

            modelBuilder.Entity("CorsoAllievo", b =>
                {
                    b.HasOne("FinsaWeb.Models.Allievo", "Allievo")
                        .WithMany("CorsiAllievi")
                        .HasForeignKey("IDAllievo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FinsaWeb.Models.EdizioneCorso", "EdizioneCorso")
                        .WithMany("CorsiAllievi")
                        .HasForeignKey("IDEdizioneCorso")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
